level: info
timeout: 5s

web:
  listen_address: 9909
  metrics_path: "/metrics"

curl_tests:
  - url: "https://slashdoom.com"
    timeout: 5s
  - url: "http://slashdoom.com"
    timeout: 5s

dns_tests:
  - host: "slashdoom.com"
    timeout: 5s

ping_tests:
  - host: "slashdoom.com"
    count: 3
    timeout: 5s

tcping_tests:
  - host: "slashdoom.com"
    port: 443
    timeout: 5s
